[logger]
level = "TRACE"
file = "calendar.log"

[database]
connection_string = "postgresql://calendar@192.168.2.100/calendar?connect_timeout=10&application_name=calendar_app"

[server]
host = "localhost"
port = "8080"
